name: Build paper

on:
  push:
  pull_request:

jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
      - uses: actions/upload-artifact@v7
        with:
          name: paper
          path: main.pdf
